baseURL = 'https://tlkahn.github.io'
languageCode = 'en-us'
title = 'Wing Kwok'
theme = 'book'
enableRobotsTXT = true
[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1
[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/tlkahn"
  weight = 10

[[menu.after]]
  name = "Twitter"
  url = "https://twitter.com/toeinriver"
  weight = 20